import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/db/prisma';
import { requireUser } from '@/lib/auth/session';
const schema=z.object({id:z.string().optional(),topicId:z.string().optional().nullable(),title:z.string().max(120).optional(),content:z.string().min(1).max(20000)});
export async function GET(req:Request){try{const user=await requireUser();const topicId=new URL(req.url).searchParams.get('topicId');const notes=await prisma.studyNote.findMany({where:{userId:user.id,...topicId?{topicId}:{}} ,orderBy:{updatedAt:'desc'}});return NextResponse.json(notes)}catch(e){return NextResponse.json({error:'Unauthorized'},{status:401})}}
export async function POST(req:Request){try{const user=await requireUser();const b=schema.parse(await req.json());if(b.topicId){const topic=await prisma.studyTopic.findUnique({where:{id:b.topicId},select:{id:true}});if(!topic)return NextResponse.json({error:'Topic not found'},{status:404})}const note=await prisma.studyNote.create({data:{userId:user.id,topicId:b.topicId||null,title:b.title?.trim()||null,content:b.content.trim()}});return NextResponse.json(note,{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
export async function PUT(req:Request){try{const user=await requireUser();const b=schema.extend({id:z.string().min(1)}).parse(await req.json());const note=await prisma.studyNote.updateMany({where:{id:b.id,userId:user.id},data:{title:b.title?.trim()||null,content:b.content.trim(),topicId:b.topicId||null}});if(!note.count)return NextResponse.json({error:'Note not found'},{status:404});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
export async function DELETE(req:Request){try{const user=await requireUser();const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Missing id'},{status:400});const r=await prisma.studyNote.deleteMany({where:{id,userId:user.id}});if(!r.count)return NextResponse.json({error:'Note not found'},{status:404});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:'Unable to delete note'},{status:400})}}
