import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/db/prisma';
import { requireUser } from '@/lib/auth/session';
const schema=z.object({id:z.string().optional(),title:z.string().min(1).max(160),type:z.string().min(1).max(40),dueDate:z.string().datetime().nullable().optional(),status:z.enum(['NOT_STARTED','IN_PROGRESS','COMPLETED']).optional()});
export async function GET(){try{const user=await requireUser();return NextResponse.json(await prisma.studyTarget.findMany({where:{userId:user.id},orderBy:[{status:'asc'},{dueDate:'asc'}]}))}catch(e){return NextResponse.json({error:'Unauthorized'},{status:401})}}
export async function POST(req:Request){try{const user=await requireUser();const b=schema.parse(await req.json());const target=await prisma.studyTarget.create({data:{userId:user.id,title:b.title.trim(),type:b.type,dueDate:b.dueDate?new Date(b.dueDate):null,status:b.status||'NOT_STARTED'}});return NextResponse.json(target,{status:201})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
export async function PUT(req:Request){try{const user=await requireUser();const b=schema.extend({id:z.string().min(1)}).parse(await req.json());const target=await prisma.studyTarget.findFirst({where:{id:b.id,userId:user.id}});if(!target)return NextResponse.json({error:'Target not found'},{status:404});const completed=b.status==='COMPLETED';const updated=await prisma.studyTarget.update({where:{id:b.id},data:{title:b.title.trim(),type:b.type,dueDate:b.dueDate?new Date(b.dueDate):null,status:b.status||target.status,completedAt:completed?new Date():null}});return NextResponse.json(updated)}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
export async function DELETE(req:Request){try{const user=await requireUser();const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Missing id'},{status:400});const r=await prisma.studyTarget.deleteMany({where:{id,userId:user.id}});if(!r.count)return NextResponse.json({error:'Target not found'},{status:404});return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:'Unable to delete target'},{status:400})}}
