'use client';
import { useState } from 'react';

export function ProgressButton({topicId, initialStatus}:{topicId:string;initialStatus:'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'}){
 const [status,setStatus]=useState(initialStatus); const [busy,setBusy]=useState(false);
 async function update(next:'IN_PROGRESS'|'COMPLETED'|'NOT_STARTED'){setBusy(true);try{const r=await fetch('/api/study/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topicId,status:next})});if(!r.ok)throw new Error();setStatus(next);}finally{setBusy(false)}}
 return <div className="flex flex-wrap items-center gap-1.5"><button disabled={busy||status==='IN_PROGRESS'} onClick={()=>update('IN_PROGRESS')} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-bold text-slate-600 transition hover:border-violet-300 hover:text-violet-600 disabled:opacity-40 dark:border-slate-700 dark:text-slate-300 dark:hover:border-violet-500 dark:hover:text-violet-300">Start</button><button disabled={busy||status==='COMPLETED'} onClick={()=>update('COMPLETED')} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold transition disabled:opacity-40 ${status==='COMPLETED'?'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300':'bg-violet-600 text-white hover:bg-violet-700'}`}>{status==='COMPLETED'?'Completed':'Mark complete'}</button>{status!=='NOT_STARTED'&&<button disabled={busy} onClick={()=>update('NOT_STARTED')} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-bold text-slate-600 transition hover:border-red-300 hover:text-red-600 disabled:opacity-40 dark:border-slate-700 dark:text-slate-300">Reset</button>}</div>
}

export function NoteBox({topicId}:{topicId:string}){
 const [content,setContent]=useState(''); const [title,setTitle]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
 async function save(){if(!content.trim())return;setBusy(true);setDone(false);try{const r=await fetch('/api/study/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topicId,title,content})});if(!r.ok)throw new Error();setContent('');setTitle('');setDone(true)}finally{setBusy(false)}}
 return <div className="rounded-lg border border-slate-200 bg-white/80 p-4 dark:border-slate-700 dark:bg-slate-900/80"><div className="text-sm font-black text-slate-900 dark:text-white">Add a note</div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Optional title" className="mt-3 h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 outline-none focus:border-violet-400 dark:border-slate-700 dark:bg-slate-950 dark:text-white"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Write what you want to remember..." rows={5} className="mt-3 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-violet-400 dark:border-slate-700 dark:bg-slate-950 dark:text-white"/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500 dark:text-slate-400">Saved to your account.</span><button onClick={save} disabled={busy||!content.trim()} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{busy?'Saving...':'Save note'}</button></div>{done&&<p className="mt-2 text-xs font-bold text-emerald-600">Note saved.</p>}</div>
}

export function TargetForm(){
 const [title,setTitle]=useState('');const [dueDate,setDueDate]=useState('');const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);
 async function save(){if(!title.trim())return;setBusy(true);setDone(false);try{const r=await fetch('/api/study/targets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,dueDate:dueDate||null,type:'STUDY'})});if(!r.ok)throw new Error();setTitle('');setDueDate('');setDone(true)}finally{setBusy(false)}}
 return <div className="rounded-2xl border border-line bg-white p-5"><div className="text-sm font-black">Set a study target</div><div className="mt-3 grid gap-3 md:grid-cols-[1fr_180px_auto]"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Finish JavaScript fundamentals" className="rounded-xl border border-line px-3 py-2 outline-none focus:border-accent"/><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="rounded-xl border border-line px-3 py-2 outline-none focus:border-accent"/><button onClick={save} disabled={busy||!title.trim()} className="rounded-xl bg-ink px-4 py-2 text-sm font-black text-white disabled:opacity-50">{busy?'Saving…':'Add target'}</button></div>{done&&<p className="mt-2 text-xs font-bold text-emerald-600">Target saved.</p>}</div>
}
